### ISSUE TITLE
Error: ENOENT: no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by sri-rang** [AnandChowdhary/run-url#1]
Hello Anand, 

Thank you for creating and maintaining this library.

Tried using it today and I received the following error

```
npx run-url https://gist.githubusercontent.com/AnandChowdhary/3c0400b29a18a2afff7a23e2a3308c22/raw/221204bc51bb7ef799363ef1e05f14c264b4a8ec/log.js

npx: installed 19 in 1.248s
up to date in 0.87s
found 0 vulnerabilities

Date 2020-10-05T17:53:50.489Z
internal/bootstrap/switches/does_own_process_state.js:128
  cachedCwd = rawMethods.cwd();
                         ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (internal/bootstrap/switches/does_own_process_state.js:128:26)
    at setopts (/home/sri/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/glob/common.js:93:21)
    at new Glob (/home/sri/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/glob/glob.js:135:3)
    at Function.glob.hasMagic (/home/sri/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/glob/glob.js:101:11)
    at Function.rimrafSync [as sync] (/home/sri/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/rimraf/rimraf.js:281:36)
    at process.<anonymous> (/home/sri/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/libnpx/index.js:151:37)
    at process.emit (events.js:315:20) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
```

when I execute the example in my readme

```
npx run-url https://gist.githubusercontent.com/AnandChowdhary/3c0400b29a18a2afff7a23e2a3308c22/raw/221204bc51bb7ef799363ef1e05f14c264b4a8ec/log.js
```

My node version is `v12.18.4` LTS branch.

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @srirangan! I just tested this locally and got no errors. Can you perhaps try using Node v14 and tell me if you still face this issue? That might point me in the right direction.

![Screen Shot 2020-10-06 at 14 22 55](https://user-images.githubusercontent.com/2841780/95180353-7cede900-07df-11eb-8651-c3648c851279.gif)

**Comment by sri-rang** [comment]
Thanks for the quick response. Works for me on `v14.13.0`.

**Comment by chandniKkpl** [comment]
Just close your terminal and start the process again it should work.

**Comment by warifmust** [comment]
@chandniKkpl works like a charm!

**Comment by ohz10** [comment]
@srirangan in another application in a galaxy far far away, I discovered you'll get this error message when you're executing node process from a directory that no longer exists - i.e. another process deleted your current working directory and then you executed node from the directory that's gone.

That's why closing your terminal and reopening it "fixes" the issue, you could also probably change your current working directory and the issue will "go away".

**Comment by alvinycheung** [comment]
Thanks for the clarity on this @SenorAgosto

**Comment by ohz10** [comment]
> Thanks for the clarity on this @SenorAgosto 

FYI, for that other project, the source of the issue was a common node dependency. 

I opened an [issue](https://github.com/dougwilson/nodejs-depd/issues/45).

I didn't look to see if that's the problem here or not.

**Comment by ifahadone** [comment]
> Hello Anand,
> 
> Thank you for creating and maintaining this library.
> 
> Tried using it today and I received the following error
> 
> ```
> npx run-url https://gist.githubusercontent.com/AnandChowdhary/3c0400b29a18a2afff7a23e2a3308c22/raw/221204bc51bb7ef799363ef1e05f14c264b4a8ec/log.js
> 
> npx: installed 19 in 1.248s
> up to date in 0.87s
> found 0 vulnerabilities
> 
> Date 2020-10-05T17:53:50.489Z
> internal/bootstrap/switches/does_own_process_state.js:128
>   cachedCwd = rawMethods.cwd();
>                          ^
> 
> Error: ENOENT: no such file or directory, uv_cwd
>     at process.wrappedCwd [as cwd] (internal/bootstrap/switches/does_own_process_state.js:128:26)
>     at setopts (/home/sri/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/glob/common.js:93:21)
>     at new Glob (/home/sri/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/glob/glob.js:135:3)
>     at Function.glob.hasMagic (/home/sri/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/glob/glob.js:101:11)
>     at Function.rimrafSync [as sync] (/home/sri/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/rimraf/rimraf.js:281:36)
>     at process.<anonymous> (/home/sri/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/libnpx/index.js:151:37)
>     at process.emit (events.js:315:20) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'uv_cwd'
> }
> ```
> 
> when I execute the example in my readme
> 
> ```
> npx run-url https://gist.githubusercontent.com/AnandChowdhary/3c0400b29a18a2afff7a23e2a3308c22/raw/221204bc51bb7ef799363ef1e05f14c264b4a8ec/log.js
> ```
> 
> My node version is `v12.18.4` LTS branch.

I stumbled upon this problem today, not using this repository script but trying to install with `npm install`,
for the future generation, if this error occurs, **make sure you are in the correct directory where package.json exists.**
Thanks!

**Comment by Hassanjankhan** [comment]
just close and re-run cmd worked for me like suggested above @SenorAgosto

**Comment by agengpangestu** [comment]
> just close and re-run cmd worked for me like suggested above @SenorAgosto

thanks bro, thats work for me
